apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces/monitoring.yaml
  - ../../base/grafana
  - ../../base/loki-monolithic
  - ../../base/prometheus
  - ../../base/tempo-monolithic
  # - ../../base/tempo-distributed
  - ../../base/otel-collector
